### ISSUE TITLE
Success after Failing not notified in default setting

### ISSUE THREAD

**Issue by jdoose** [halkeye/hubot-jenkins-notifier#12]
The default setting for notification is Fs: Notify alway on failure, and for a changed build status on success.
If a job failed and is succeeding afterwards no notification is sent.
I guess (but I am not sure) that's because line 201 `if (/S/.test(this.query.onFinished)) {` which should use `shouldNotify`rather that test for `S`.

**Comment by halkeye** [comment]
yea I think you are right

I managed to figure out a test case that triggers this.

**Comment by jdoose** [comment]
Great work, thanks!
