### ISSUE TITLE
Document default setting for notification in readme

### ISSUE THREAD

**Issue by jdoose** [halkeye/hubot-jenkins-notifier#13]
not a bug, just a documentation thing:
The readme states:
`onStart`/`onFinished`: Notification strategy: [Ff][Ss] which stands for "Failure" and "Success". Capitalized letter means: notify always. Small letter means: notify only if buildstatus has changed
It would be great if this could also mention the default setting if no notification strategy is given.

**Comment by halkeye** [comment]
These are on my list. Havn't forgotten about them, just kinda busy. Hopefully this weekend
