### ISSUE TITLE
Parse build response of "UNSTABLE"

### ISSUE THREAD

**Issue by vwbusguy** [halkeye/hubot-jenkins-notifier#19]
The current script only parses build status of "SUCCESS" and "FAILURE" but Jenkins currently offers an "UNSTABLE" status when the build succeeds, but tests fail.  This causes the plugin to fail to notify the room of the build status.  I recommend either adding unstable to failure case scenario, or adjusting the parsing options to accommodate it directly.  If I have time today I might put together a pull request.

**Comment by halkeye** [comment]
Is there an easy way to generate this state so I can create a test case?
Maybe just "exit 1" shell script?

**Comment by vwbusguy** [comment]
I've been asked to generate it with maven. Mvn package builds successfully
but Mvn test does not. Because it fails test cases, it results in UNSTABLE.
You could have a simple assert false test case.

**Comment by halkeye** [comment]
Oh okay. So exit code 0, but a post build step marking it unstable?

I think I can set that up.

Probably won't get to it till monday

**Comment by vwbusguy** [comment]
Here's the Jenkins documentation on how to set it up generically:
https://jenkins.io/doc/pipeline/tour/tests-and-artifacts/

**Comment by halkeye** [comment]
shit, totally forgot to do this sorry

**Comment by halkeye** [comment]
I have a patch to treat unstable as failed.

**Comment by halkeye** [comment]
Branch: unstable-as-failed
Commit: 6cb040d

If you are able to test it at all (and I added unit tests) I'll publish

**Comment by halkeye** [comment]
Merged

Released 1.1.0

**Comment by vwbusguy** [comment]
Sorry, I didn't see your followup until just now, but many thanks!
