### ISSUE TITLE
Hubot not responding to jenkins command 

### ISSUE THREAD

**Issue by npithadi** [halkeye/hubot-jenkins-notifier#48]
We  have cam-bot (hubot name, installed on my laptop) not responding to jenkins build command. 

Command:-
"cam-bot  build orpheus-cam-service-composer-ui master "

cam-bot> Command 'cam-bot  build orpheus-cam-service-composer-ui master' called in room 'Shell' by 'Shell'
User { id: '1', name: 'Shell', room: 'Shell' }
[Wed Mar 21 2018 10:05:37 GMT+0530 (IST)] INFO https://orpheus-jenkins.swg-devops.com:8443/job/orpheus-cam-service-composer-ui/job/master/buildWithParameters?
401
null
Failed to submit jenkins build. rc: 401, error: null

what could be issue with this ?

**Comment by halkeye** [comment]
This plugin doesn't accept commands, its all about being notified by jenkins about job state.

401 says you need to provide credentials. I don't know which plugin adds the 'build' command
