### ISSUE TITLE
Does not seem to work with Jenkins 1.619

### ISSUE THREAD

**Issue by tholu** [halkeye/hubot-jenkins-notifier#5]
No error in Jenkins console output, but no message from my hubot in the room either. Is there a curl command I can try with?

**Comment by halkeye** [comment]
Um... Not offhand, there are a bunch of test cases though.
https://github.com/halkeye/hubot-jenkins-notifier/blob/master/src/test/hubot-jenkins-notifier_test.coffee

So something like
```curl -X POST -H 'Content-Type: application/json' -d "{"name":"JobName","url":"JobUrl","build":{"number":1,"phase":"FINISHED","status":"FAILURE", "url":"job/project%20name/", "full_url":"http://ci.jenkins.org/job/project%20name/5", "parameters":{"branch":"master"}}}}' http://<hubot-host>:<hubot-port>/hubot/jenkins-notify?room=<room>```

I haven't tested this as I'm not at home right now. I can try this out on my real jenkins on the weekend.

**Comment by tholu** [comment]
I will try that, so <room> has to be prefixed with %23, correct? Is the room name case sensitive? This is not immediately clear from the README currently. Would be great if you could try that on your real jenkins as well!

**Comment by tholu** [comment]
```
curl -X POST -H 'Content-Type: application/json' -d '{"name":"JobName","url":"JobUrl","build":{"number":1,"phase":"FINISHED","status":"FAILURE", "url":"job/project%20name/", "full_url":"http://ci.jenkins.org/job/project%20name/5", "parameters":{"branch":"master"}}}' http://<hubot-host>:<hubot-port>/hubot/jenkins-notify?room=<room>
```

Fixed so that there are no parsing errors, but my bot does not do anything when notified.

**Comment by halkeye** [comment]
What version of hubot do you use? I'll run my tests again when I get home tomorrow.

**Comment by halkeye** [comment]
Did this ever work? or is this new setting up?

I was able to get it working on slack:

    http://localhost:5555/hubot/jenkins-notify?room=%23general&notstrat=FS

One thing I noticed so I'll have to update the docs is that if you want it to always notify, you should set notstrat to FS

Not strat was merged in from hubot-scripts before they deprecated it but I missed merging in docs
https://github.com/github/hubot-scripts/blob/master/src/scripts/jenkins-notifier.coffee#L17

    # Notification Strategy is [Ff][Ss] which stands for "Failure" and "Success"
    # Capitalized letter means: notify always
    # small letter means: notify only if buildstatus has changed
    # "Fs" is the default

Also, if your room starts with a # (depends on the adapter), then yea, you'd need to add a %23, which is a encoded #. You have to encode parameters in your url

**Comment by tholu** [comment]
This is a new setup and I did not get it to work yet, but instead of Slack I'm using https://github.com/sdelements/lets-chat

I'm using hubot@2.13.2.

**Comment by tholu** [comment]
I found the issue. With lets-chat, you have to use the room id, which you can see in the address bar, when entering the room. So the problem was specific to the adapter all the time. Sorry!
